<template>
  <main class="w-full h-full bg-none relative bg-black/30 flex justify-center items-center">
    <div class="loadingio-spinner-double-ring-yw11lkllc2">
      <div class="ldio-w2u5af903gb">
        <div></div>
        <div></div>
        <div><div></div></div>
        <div><div></div></div>
      </div>
    </div>
  </main>
</template>
<script lang="ts">
export default {
  name: 'loading6',
}
</script>
<script lang="ts" setup></script>


<style type="text/css" scoped>
@keyframes ldio-w2u5af903gb {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-w2u5af903gb div { box-sizing: border-box!important }
.ldio-w2u5af903gb > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #e15b64 transparent #e15b64 transparent;
  animation: ldio-w2u5af903gb 1s linear infinite;
}

.ldio-w2u5af903gb > div:nth-child(2), .ldio-w2u5af903gb > div:nth-child(4) {
  width: 108px;
  height: 108px;
  top: 46px;
  left: 46px;
  animation: ldio-w2u5af903gb 1s linear infinite reverse;
}
.ldio-w2u5af903gb > div:nth-child(2) {
  border-color: transparent #f8b26a transparent #f8b26a
}
.ldio-w2u5af903gb > div:nth-child(3) { border-color: transparent }
.ldio-w2u5af903gb > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-w2u5af903gb > div:nth-child(3) div:before, .ldio-w2u5af903gb > div:nth-child(3) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #e15b64;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #e15b64;
}
.ldio-w2u5af903gb > div:nth-child(3) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #e15b64;
}

.ldio-w2u5af903gb > div:nth-child(4) { border-color: transparent; }
.ldio-w2u5af903gb > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-w2u5af903gb > div:nth-child(4) div:before, .ldio-w2u5af903gb > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 30px;
  background: #f8b26a;
  border-radius: 50%;
  box-shadow: 0 92px 0 0 #f8b26a;
}
.ldio-w2u5af903gb > div:nth-child(4) div:after {
  left: -16px;
  top: 30px;
  box-shadow: 92px 0 0 0 #f8b26a;
}
.loadingio-spinner-double-ring-yw11lkllc2 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-w2u5af903gb {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-w2u5af903gb div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>