<template>
  <main class="w-full h-full bg-none relative bg-black/30 flex justify-center items-center">
    <div class="loadingio-spinner-dual-ball-o5jrwsdxbsr">
      <div class="ldio-qo5jhaccn2">
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </main>
</template>
<script lang="ts">
export default {
  name: 'loading4',
}
</script>
<script lang="ts" setup></script>

<style type="text/css" scoped>
@keyframes ldio-qo5jhaccn2-o {
  0% {
    opacity: 1;
    transform: translate(0 0);
  }
  49.99% {
    opacity: 1;
    transform: translate(80px, 0);
  }
  50% {
    opacity: 0;
    transform: translate(80px, 0);
  }
  100% {
    opacity: 0;
    transform: translate(0, 0);
  }
}
@keyframes ldio-qo5jhaccn2 {
  0% {
    transform: translate(0, 0);
  }
  50% {
    transform: translate(80px, 0);
  }
  100% {
    transform: translate(0, 0);
  }
}
.ldio-qo5jhaccn2 div {
  position: absolute;
  width: 80px;
  height: 80px;
  border-radius: 50%;
  top: 60px;
  left: 20px;
}
.ldio-qo5jhaccn2 div:nth-child(1) {
  background: #e90c59;
  animation: ldio-qo5jhaccn2 1s linear infinite;
  animation-delay: -0.5s;
}
.ldio-qo5jhaccn2 div:nth-child(2) {
  background: #46dff0;
  animation: ldio-qo5jhaccn2 1s linear infinite;
  animation-delay: 0s;
}
.ldio-qo5jhaccn2 div:nth-child(3) {
  background: #e90c59;
  animation: ldio-qo5jhaccn2-o 1s linear infinite;
  animation-delay: -0.5s;
}
.loadingio-spinner-dual-ball-o5jrwsdxbsr {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-qo5jhaccn2 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-qo5jhaccn2 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
